// admin-api v13 / CDP-2B patch2 (segment_needs_review mapping)
// ── CDP-3C ADDITIVE (v13 → v13+consent): iki SALT-OKUNUR action eklendi ──
//   - q_member_consent           -> admin_q_member_consent(p_actor,p_user_id)  [super_admin/support/crm]
//   - marketing_readiness_check  -> marketing_readiness_check()                [super_admin/support/crm]
//   Her ikisi de READ; WRITE_ACTIONS'a EKLENMEDİ -> admin opt-in VEREMEZ (consent yazımı yok).
//   Yanıtlar RPC allowlist'iyle sınırlı: ham HMAC/fingerprint/idempotency/request_id/evidence DÖNMEZ.
//   Mevcut CDP-2B/2C admin action'ları, rol kapıları, rate-limit, kill-switch DEĞİŞMEDEN korunur.
import { createClient } from "jsr:@supabase/supabase-js@2";
const URL  = Deno.env.get("SUPABASE_URL")!;
const ANON = Deno.env.get("SUPABASE_ANON_KEY")!;
const SRK  = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ENV_KILL = (Deno.env.get("ADMIN_API_KILL") ?? "") === "1";
const MAX_BODY = 8 * 1024;
const ALLOWED_ORIGINS = ["https://www.asalocal.club", ...(Deno.env.get("ADMIN_ALLOWED_ORIGIN") ? [Deno.env.get("ADMIN_ALLOWED_ORIGIN")!] : [])];
function cors(origin){ const allow = !!origin && ALLOWED_ORIGINS.includes(origin); const h={"Vary":"Origin","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"authorization, apikey, x-client-info, content-type"}; if(allow)h["Access-Control-Allow-Origin"]=origin; return {h,allow,present:!!origin}; }
const ROLE_SETS = { counts:"ANY_ADMIN", member_search:["super_admin","support"], member_360:["super_admin","support"], comment_search:["super_admin","moderator"], comment_set_hidden:["super_admin","moderator"], member_set_blocked:["super_admin","support"], adjust_points:["super_admin"], content_rollback:["super_admin","content_editor"], audit_search:["super_admin"], audit_detail:["super_admin"], content_versions:["super_admin","content_editor"], cities_overview:["super_admin","content_editor"], city_health:["super_admin","content_editor"], member_set_note:["super_admin","support"], member_set_segment:["super_admin","support"], segment_preview:["super_admin","crm","analyst"], segment_list:["super_admin","crm","analyst"], segment_upsert:["super_admin","crm"], segment_run:["super_admin","crm"], segment_duplicate:["super_admin","crm"], segment_set_active:["super_admin","crm"], events_list:["super_admin","crm","analyst"], segment_taxonomy:["super_admin","crm","analyst"], segment_member_search:["super_admin","crm","analyst"], member_360_by_ref:["super_admin","support"], q_member_consent:["super_admin","support","crm"], marketing_readiness_check:["super_admin","support","crm"] };
const WRITE_ACTIONS = new Set(["comment_set_hidden","member_set_blocked","adjust_points","content_rollback","member_set_note","member_set_segment","segment_upsert","segment_run","segment_duplicate","segment_set_active"]);
const LIMITS = { counts:{min:30,day:2000}, member_search:{min:20,day:500}, member_360:{min:10,day:200}, comment_search:{min:60,day:1000}, comment_set_hidden:{min:20,day:200}, member_set_blocked:{min:5,day:30}, adjust_points:{min:10,day:100}, content_rollback:{min:10,day:100}, audit_search:{min:60,day:2000}, audit_detail:{min:120,day:5000}, content_versions:{min:60,day:2000}, cities_overview:{min:60,day:2000}, city_health:{min:120,day:4000}, member_set_note:{min:20,day:300}, member_set_segment:{min:20,day:300}, segment_preview:{min:60,day:3000}, segment_list:{min:60,day:3000}, segment_upsert:{min:30,day:500}, segment_run:{min:60,day:2000}, segment_duplicate:{min:20,day:300}, segment_set_active:{min:30,day:500}, events_list:{min:120,day:5000}, segment_taxonomy:{min:120,day:5000}, segment_member_search:{min:60,day:2000}, member_360_by_ref:{min:10,day:200}, q_member_consent:{min:60,day:2000}, marketing_readiness_check:{min:60,day:2000} };
const REASONS=["spam","inappropriate","harassment","misleading","user_request","security","other"];
const ENTITIES=["venues","cities","site_content","ads"];
const AUDIT_ACTIONS=["insert","update","delete"];
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const CITY_CODE_RE=/^[a-z]{2}-[a-z]{3}$/;
const REF_RE=/^[0-9a-f]{12,64}$/i;
const rid=()=>crypto.randomUUID();
const sleep=(ms)=>new Promise((r)=>setTimeout(r,ms));
function json(status,body,request_id,ch){ return new Response(JSON.stringify(body),{status,headers:{...ch,"Content-Type":"application/json","X-Request-Id":request_id,"X-Content-Type-Options":"nosniff","Cache-Control":"no-store"}}); }
async function rpcBool(client,fn,args){ let attempt=0; while(true){ const {data,error}=await client.rpc(fn,args); if(!error)return {kind:"value",value:data===true}; attempt++; if(attempt>=3)return {kind:"tech_error"}; await sleep(60*attempt+Math.floor(Math.random()*120)); } }
function mapRpcError(msg){ const m=msg||""; if(m.includes("admin writes disabled")||m.includes("admin api disabled"))return{status:503,error:"admin_temporarily_disabled"}; if(m.includes("idempotency_conflict"))return{status:409,error:"idempotency_conflict"}; if(m.includes("would_make_negative"))return{status:409,error:"would_make_negative"}; if(m.includes("cannot_target_self"))return{status:409,error:"cannot_target_self"}; if(m.includes("cannot_target_admin"))return{status:409,error:"cannot_target_admin"}; if(m.includes("target_not_found"))return{status:404,error:"target_not_found"}; if(m.includes("segment_needs_review"))return{status:409,error:"segment_needs_review"}; if(m.includes("not authorized"))return{status:403,error:"forbidden"}; if(m.includes("not_admin"))return{status:403,error:"not_admin"}; if(m.includes("forbidden"))return{status:403,error:"forbidden"}; if(m.includes("not_found"))return{status:404,error:"not_found"}; if(m.includes("legacy_not_allowed"))return{status:400,error:"legacy_not_allowed"}; if(m.includes("bad_field")||m.includes("bad_value")||m.includes("bad_match")||m.includes("bad_groups")||m.includes("bad_rules")||m.includes("too_many_groups")||m.includes("too_many_rules")||m.includes("bad_name")||m.includes("bad_description"))return{status:400,error:"bad_input"}; if(m.includes("bad_delta")||m.includes("bad_reason")||m.includes("bad_note")||m.includes("bad_segment")||m.includes("note_too_long")||m.includes("idem_required"))return{status:400,error:"bad_input"}; return{status:500,error:"internal"}; }
Deno.serve(async (req)=>{ const request_id=rid(); const origin=req.headers.get("Origin"); const {h:ch,allow:originAllowed,present:originPresent}=cors(origin);
 if(req.method==="OPTIONS"){ if(originPresent&&!originAllowed)return new Response(null,{status:403}); return new Response("ok",{headers:ch}); }
 if(originPresent&&!originAllowed)return json(403,{error:"origin_not_allowed"},request_id,ch);
 if(req.method!=="POST")return json(405,{error:"method_not_allowed"},request_id,ch);
 if(ENV_KILL)return json(503,{error:"admin_temporarily_disabled"},request_id,ch);
 const authz=req.headers.get("Authorization")??""; const mtok=authz.match(/^Bearer\s+(.+)$/); if(!mtok)return json(401,{error:"missing_bearer"},request_id,ch); const token=mtok[1];
 if(!(req.headers.get("Content-Type")??"").includes("application/json"))return json(415,{error:"unsupported_media_type"},request_id,ch);
 const raw=await req.text(); if(raw.length>MAX_BODY)return json(413,{error:"payload_too_large"},request_id,ch);
 let payload; try{payload=JSON.parse(raw||"{}");}catch{return json(400,{error:"bad_json"},request_id,ch);} const action=payload?.action; const params=payload?.params??{};
 if(!action||!(action in ROLE_SETS))return json(400,{error:"unknown_action"},request_id,ch);
 const userClient=createClient(URL,ANON,{global:{headers:{Authorization:`Bearer ${token}`}}}); const {data:{user},error:uerr}=await userClient.auth.getUser(); if(uerr||!user)return json(401,{error:"invalid_token"},request_id,ch);
 const adm=await rpcBool(userClient,"is_current_user_admin",{}); if(adm.kind==="tech_error")return json(503,{error:"admin_temporarily_disabled"},request_id,ch); if(adm.value!==true)return json(403,{error:"not_admin"},request_id,ch);
 const need=ROLE_SETS[action]; if(need!=="ANY_ADMIN"){ let anyTrue=false,anyTechError=false; for(const role of need){ const r=await rpcBool(userClient,"current_user_has_admin_role",{role_name:role}); if(r.kind==="tech_error"){anyTechError=true;continue;} if(r.value===true){anyTrue=true;break;} } if(anyTrue){} else if(anyTechError)return json(503,{error:"admin_temporarily_disabled"},request_id,ch); else return json(403,{error:"forbidden"},request_id,ch); }
 const v=validate(action,params); if(!v.ok)return json(400,{error:v.error},request_id,ch);
 const svc=createClient(URL,SRK,{auth:{persistSession:false}});
 { const {data:enabled,error:sErr}=await svc.rpc("admin_api_status"); if(sErr||enabled!==true)return json(503,{error:"admin_temporarily_disabled"},request_id,ch); }
 if(WRITE_ACTIONS.has(action)){ const {data:wEnabled,error:wErr}=await svc.rpc("admin_writes_status"); if(wErr||wEnabled!==true)return json(503,{error:"writes_temporarily_disabled"},request_id,ch); }
 const lim=LIMITS[action]; const {data:allowed,error:rlErr}=await svc.rpc("admin_rate_check",{p_actor:user.id,p_action:action,p_max_min:lim.min,p_max_day:lim.day}); if(rlErr)return json(500,{error:"internal"},request_id,ch); if(allowed!==true)return json(429,{error:"rate_limited"},request_id,ch);
 try{ let data,err;
  if(action==="counts"){({data,error:err}=await svc.rpc("admin_q_counts",{p_actor:user.id}));}
  else if(action==="member_search"){({data,error:err}=await svc.rpc("admin_q_member_search",{p_actor:user.id,p_query:v.q,p_search_type:v.search_type,p_blocked:v.blocked,p_limit:v.limit,p_offset:v.offset,p_request_id:request_id}));}
  else if(action==="member_360"){({data,error:err}=await svc.rpc("admin_q_member_360",{p_actor:user.id,p_target:v.target,p_request_id:request_id}));}
  else if(action==="comment_search"){({data,error:err}=await svc.rpc("admin_q_comment_search",{p_actor:user.id,p_city:v.city,p_venue:v.venue,p_visibility:v.visibility,p_user:v.user,p_from:v.from,p_to:v.to,p_limit:v.limit,p_offset:v.offset,p_request_id:request_id}));}
  else if(action==="comment_set_hidden"){({data,error:err}=await svc.rpc("admin_w_comment_set_hidden",{p_actor:user.id,p_target:v.target,p_desired:v.desired,p_reason:v.reason,p_note:v.note,p_idem:v.idem,p_request_id:request_id}));}
  else if(action==="member_set_blocked"){({data,error:err}=await svc.rpc("admin_w_member_set_blocked",{p_actor:user.id,p_target:v.target,p_desired:v.desired,p_reason:v.reason,p_note:v.note,p_idem:v.idem,p_request_id:request_id}));}
  else if(action==="adjust_points"){({data,error:err}=await svc.rpc("admin_w_adjust_points",{p_actor:user.id,p_target:v.target,p_delta:v.delta,p_reason:v.reason,p_note:v.note,p_idem:v.idem,p_request_id:request_id}));}
  else if(action==="content_rollback"){({data,error:err}=await svc.rpc("admin_w_content_rollback",{p_actor:user.id,p_key:v.key,p_version:v.version,p_reason:v.reason,p_idem:v.idem,p_request_id:request_id}));}
  else if(action==="audit_search"){({data,error:err}=await svc.rpc("admin_q_audit_search",{p_actor:user.id,p_from:v.from,p_to:v.to,p_actor_uid:v.actor_uid,p_entity:v.entity,p_action:v.aaction,p_entity_id:v.entity_id,p_limit:v.limit,p_offset:v.offset,p_request_id:request_id}));}
  else if(action==="audit_detail"){({data,error:err}=await svc.rpc("admin_q_audit_detail",{p_actor:user.id,p_id:v.id,p_request_id:request_id}));}
  else if(action==="content_versions"){({data,error:err}=await svc.rpc("admin_q_content_versions",{p_actor:user.id,p_key:v.key,p_limit:v.limit,p_offset:v.offset,p_request_id:request_id}));}
  else if(action==="member_set_note"){({data,error:err}=await svc.rpc("admin_w_member_set_note",{p_actor:user.id,p_target:v.target,p_note:v.note,p_idem:v.idem,p_request_id:request_id}));}
  else if(action==="member_set_segment"){({data,error:err}=await svc.rpc("admin_w_member_set_segment",{p_actor:user.id,p_target:v.target,p_segment:v.segment,p_idem:v.idem,p_request_id:request_id}));}
  else if(action==="segment_preview"){({data,error:err}=await svc.rpc("admin_q_segment_preview",{p_actor:user.id,p_def:v.definition}));}
  else if(action==="segment_list"){({data,error:err}=await svc.rpc("admin_q_segment_list",{p_actor:user.id}));}
  else if(action==="segment_upsert"){({data,error:err}=await svc.rpc("admin_w_segment_upsert",{p_actor:user.id,p_id:v.id,p_name:v.name,p_description:v.description,p_def:v.definition,p_active:v.active,p_request_id:request_id}));}
  else if(action==="segment_run"){({data,error:err}=await svc.rpc("admin_w_segment_run",{p_actor:user.id,p_id:v.id,p_request_id:request_id}));}
  else if(action==="segment_duplicate"){({data,error:err}=await svc.rpc("admin_w_segment_duplicate",{p_actor:user.id,p_id:v.id,p_request_id:request_id}));}
  else if(action==="segment_set_active"){({data,error:err}=await svc.rpc("admin_w_segment_set_active",{p_actor:user.id,p_id:v.id,p_active:v.active,p_request_id:request_id}));}
  else if(action==="events_list"){({data,error:err}=await svc.rpc("admin_q_events_v2",{p_actor:user.id,p_from:v.from,p_to:v.to,p_type:v.type,p_city_code:v.city_code,p_ref:v.ref,p_limit:v.limit,p_offset:v.offset}));}
  else if(action==="segment_taxonomy"){({data,error:err}=await svc.rpc("admin_q_segment_taxonomy",{p_actor:user.id}));}
  else if(action==="segment_member_search"){({data,error:err}=await svc.rpc("admin_q_segment_member_search",{p_actor:user.id,p_query:v.q,p_limit:v.limit}));}
  else if(action==="member_360_by_ref"){({data,error:err}=await svc.rpc("admin_q_member_360_by_ref",{p_actor:user.id,p_stable_ref:v.ref,p_request_id:request_id}));}
  else if(action==="cities_overview"){({data,error:err}=await svc.rpc("admin_q_cities_overview",{p_actor:user.id}));}
  else if(action==="city_health"){({data,error:err}=await svc.rpc("admin_q_city_health",{p_actor:user.id,p_city:v.city}));}
  // ── CDP-3C SALT-OKUNUR consent görünümü + pazarlama readiness (yazma yok) ──
  else if(action==="q_member_consent"){({data,error:err}=await svc.rpc("admin_q_member_consent",{p_actor:user.id,p_user_id:v.user_id}));}
  else if(action==="marketing_readiness_check"){({data,error:err}=await svc.rpc("marketing_readiness_check",{}));}
  if(err){ const mapped=mapRpcError(String(err.message??"")); return json(mapped.status,{error:mapped.error},request_id,ch); }
  return json(200,{request_id,data},request_id,ch);
 }catch(_e){ return json(500,{error:"internal"},request_id,ch); }
});
function clampInt(x,def,lo,hi){ const n=Number.isFinite(+x)?Math.trunc(+x):def; return Math.max(lo,Math.min(hi,n)); }
function validate(action,p){
 if(action==="counts")return{ok:true};
 if(action==="member_search"){ const search_type=p?.search_type??"name"; if(!["name","email","filter"].includes(search_type))return{ok:false,error:"bad_search_type"}; let q=typeof p?.q==="string"?p.q.trim():null; if(q==="")q=null; if(search_type==="filter"&&q!==null)return{ok:false,error:"q_not_allowed_for_filter"}; if((search_type==="name"||search_type==="email")&&q===null)return{ok:false,error:"q_required"}; if(q!==null&&(q.length<2||q.length>100))return{ok:false,error:"bad_query_length"}; if((Number(p?.offset)||0)>10000)return{ok:false,error:"offset_too_large"}; return{ok:true,q,search_type,blocked:typeof p?.blocked==="boolean"?p.blocked:null,limit:clampInt(p?.limit,25,1,50),offset:clampInt(p?.offset,0,0,10000)}; }
 if(action==="member_360"){ if(typeof p?.target!=="string"||!UUID_RE.test(p.target))return{ok:false,error:"bad_target"}; return{ok:true,target:p.target}; }
 if(action==="comment_search"){ const visibility=p?.visibility??"all"; if(!["all","visible","hidden"].includes(visibility))return{ok:false,error:"bad_visibility"}; const strOrNull=(x,max=120)=>(typeof x==="string"&&x.trim()!==""?x.trim().slice(0,max):null); let user=null; if(p?.user!=null){ if(typeof p.user!=="string"||!UUID_RE.test(p.user))return{ok:false,error:"bad_user"}; user=p.user; } const dt=(x)=>(typeof x==="string"&&x.length>=8&&x.length<=40?x:null); return{ok:true,visibility,city:strOrNull(p?.city),venue:strOrNull(p?.venue),user,from:dt(p?.from),to:dt(p?.to),limit:clampInt(p?.limit,25,1,50),offset:clampInt(p?.offset,0,0,10000)}; }
 if(action==="comment_set_hidden"||action==="member_set_blocked"){ if(typeof p?.desired!=="boolean")return{ok:false,error:"bad_desired"}; if(typeof p?.reason!=="string"||!REASONS.includes(p.reason))return{ok:false,error:"bad_reason"}; let note=null; if(p?.note!=null){ if(typeof p.note!=="string")return{ok:false,error:"bad_note"}; note=p.note.slice(0,280); } if(typeof p?.idempotency_key!=="string"||!UUID_RE.test(p.idempotency_key))return{ok:false,error:"bad_idem"}; if(action==="comment_set_hidden"){ const n=Number(p?.target); if(!Number.isInteger(n)||n<=0)return{ok:false,error:"bad_target"}; return{ok:true,target:n,desired:p.desired,reason:p.reason,note,idem:p.idempotency_key}; } else { if(typeof p?.target!=="string"||!UUID_RE.test(p.target))return{ok:false,error:"bad_target"}; return{ok:true,target:p.target,desired:p.desired,reason:p.reason,note,idem:p.idempotency_key}; } }
 if(action==="adjust_points"){ if(typeof p?.target!=="string"||!UUID_RE.test(p.target))return{ok:false,error:"bad_target"}; const d=Number(p?.delta); if(!Number.isInteger(d)||d===0||d<-100||d>100)return{ok:false,error:"bad_delta"}; if(typeof p?.reason!=="string"||p.reason.trim().length<3||p.reason.length>280)return{ok:false,error:"bad_reason"}; if(typeof p?.note!=="string"||p.note.trim().length<3||p.note.length>280)return{ok:false,error:"bad_note"}; if(typeof p?.idempotency_key!=="string"||!UUID_RE.test(p.idempotency_key))return{ok:false,error:"bad_idem"}; return{ok:true,target:p.target,delta:d,reason:p.reason.trim(),note:p.note.trim(),idem:p.idempotency_key}; }
 if(action==="content_rollback"){ if(typeof p?.key!=="string"||p.key.trim()===""||p.key.length>200)return{ok:false,error:"bad_key"}; const ver=Number(p?.version); if(!Number.isInteger(ver)||ver<=0)return{ok:false,error:"bad_version"}; if(typeof p?.reason!=="string"||p.reason.trim().length<3||p.reason.length>280)return{ok:false,error:"bad_reason"}; if(typeof p?.idempotency_key!=="string"||!UUID_RE.test(p.idempotency_key))return{ok:false,error:"bad_idem"}; return{ok:true,key:p.key.trim(),version:ver,reason:p.reason.trim(),idem:p.idempotency_key}; }
 if(action==="audit_search"){ const dt=(x)=>(typeof x==="string"&&x.length>=8&&x.length<=40?x:null); let actor_uid=null; if(p?.actor_uid!=null){ if(typeof p.actor_uid!=="string"||!UUID_RE.test(p.actor_uid))return{ok:false,error:"bad_actor"}; actor_uid=p.actor_uid; } let entity=null; if(p?.entity!=null){ if(!ENTITIES.includes(p.entity))return{ok:false,error:"bad_entity"}; entity=p.entity; } let aaction=null; if(p?.action!=null){ if(!AUDIT_ACTIONS.includes(p.action))return{ok:false,error:"bad_action_filter"}; aaction=p.action; } const eid=(typeof p?.entity_id==="string"&&p.entity_id.trim()!=="")?p.entity_id.trim().slice(0,200):null; return{ok:true,from:dt(p?.from),to:dt(p?.to),actor_uid,entity,aaction,entity_id:eid,limit:clampInt(p?.limit,25,1,100),offset:clampInt(p?.offset,0,0,100000)}; }
 if(action==="audit_detail"){ const n=Number(p?.id); if(!Number.isInteger(n)||n<=0)return{ok:false,error:"bad_id"}; return{ok:true,id:n}; }
 if(action==="content_versions"){ if(typeof p?.key!=="string"||p.key.trim()===""||p.key.length>200)return{ok:false,error:"bad_key"}; return{ok:true,key:p.key.trim(),limit:clampInt(p?.limit,20,1,100),offset:clampInt(p?.offset,0,0,100000)}; }
 if(action==="member_set_note"){ if(typeof p?.target!=="string"||!UUID_RE.test(p.target))return{ok:false,error:"bad_target"}; let note=null; if(p?.note!=null){ if(typeof p.note!=="string")return{ok:false,error:"bad_note"}; note=p.note; if(note.length>2000)return{ok:false,error:"bad_note"}; } if(typeof p?.idempotency_key!=="string"||!UUID_RE.test(p.idempotency_key))return{ok:false,error:"bad_idem"}; return{ok:true,target:p.target,note,idem:p.idempotency_key}; }
 if(action==="member_set_segment"){ if(typeof p?.target!=="string"||!UUID_RE.test(p.target))return{ok:false,error:"bad_target"}; let segment=null; if(p?.segment!=null){ if(typeof p.segment!=="string")return{ok:false,error:"bad_segment"}; segment=p.segment; if(segment.length>200)return{ok:false,error:"bad_segment"}; } if(typeof p?.idempotency_key!=="string"||!UUID_RE.test(p.idempotency_key))return{ok:false,error:"bad_idem"}; return{ok:true,target:p.target,segment,idem:p.idempotency_key}; }
 if(action==="segment_preview"){ if(typeof p?.definition!=="object"||p.definition===null||Array.isArray(p.definition))return{ok:false,error:"bad_definition"}; return{ok:true,definition:p.definition}; }
 if(action==="segment_list")return{ok:true};
 if(action==="segment_upsert"){ let id=null; if(p?.id!=null){ if(typeof p.id!=="string"||!UUID_RE.test(p.id))return{ok:false,error:"bad_id"}; id=p.id; } if(typeof p?.name!=="string"||p.name.trim()===""||p.name.length>120)return{ok:false,error:"bad_name"}; let description=null; if(p?.description!=null){ if(typeof p.description!=="string"||p.description.length>500)return{ok:false,error:"bad_description"}; description=p.description; } if(typeof p?.definition!=="object"||p.definition===null||Array.isArray(p.definition))return{ok:false,error:"bad_definition"}; return{ok:true,id,name:p.name.trim(),description,definition:p.definition,active:typeof p?.active==="boolean"?p.active:true}; }
 if(action==="segment_run"||action==="segment_duplicate"){ if(typeof p?.id!=="string"||!UUID_RE.test(p.id))return{ok:false,error:"bad_id"}; return{ok:true,id:p.id}; }
 if(action==="segment_set_active"){ if(typeof p?.id!=="string"||!UUID_RE.test(p.id))return{ok:false,error:"bad_id"}; if(typeof p?.active!=="boolean")return{ok:false,error:"bad_active"}; return{ok:true,id:p.id,active:p.active}; }
 if(action==="events_list"){ const dstr=(x)=>(typeof x==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(x)?x:null); const TYPES=["signup","trip_created","plan_created","favorite_added","comment_posted","reaction_added","points_changed","decision_used"]; let type=null; if(p?.type!=null){ if(!TYPES.includes(p.type))return{ok:false,error:"bad_type"}; type=p.type; } let city_code=null; if(p?.city_code!=null){ if(typeof p.city_code!=="string"||!CITY_CODE_RE.test(p.city_code))return{ok:false,error:"bad_city_code"}; city_code=p.city_code; } let ref=null; if(p?.ref!=null){ if(typeof p.ref!=="string"||!REF_RE.test(p.ref))return{ok:false,error:"bad_ref"}; ref=p.ref; } return{ok:true,from:dstr(p?.from),to:dstr(p?.to),type,city_code,ref,limit:clampInt(p?.limit,50,1,100),offset:clampInt(p?.offset,0,0,100000)}; }
 if(action==="segment_taxonomy")return{ok:true};
 if(action==="segment_member_search"){ let q=typeof p?.q==="string"?p.q.trim():null; if(q==="")q=null; if(q!==null&&q.length>100)return{ok:false,error:"bad_query_length"}; return{ok:true,q,limit:clampInt(p?.limit,20,1,50)}; }
 if(action==="member_360_by_ref"){ if(typeof p?.ref!=="string"||!REF_RE.test(p.ref))return{ok:false,error:"bad_ref"}; return{ok:true,ref:p.ref}; }
 if(action==="cities_overview")return{ok:true};
 if(action==="city_health"){ if(typeof p?.city!=="string"||p.city.trim()===""||p.city.length>80)return{ok:false,error:"bad_city"}; return{ok:true,city:p.city.trim()}; }
 // ── CDP-3C: SALT-OKUNUR consent görünümü — yalnız hedef user_id (UUID); başka alan/write yok ──
 if(action==="q_member_consent"){ if(typeof p?.user_id!=="string"||!UUID_RE.test(p.user_id))return{ok:false,error:"bad_user_id"}; return{ok:true,user_id:p.user_id}; }
 // ── CDP-3C: pazarlama readiness — parametresiz salt-okuma ──
 if(action==="marketing_readiness_check")return{ok:true};
 return{ok:false,error:"unknown_action"};
}
